### ISSUE TITLE
route希望可以自定义添加对象信息 现在自己添加对象信息就会导致插件运行效果不正确 没有正确加载布局 

### ISSUE THREAD

**Issue by sharebravery** [uni-helper/vite-plugin-uni-layouts#12]
### 对问题的清晰和简明的描述

加入tabBar的信息之后 布局没有正确加载 不生效了
``` 
<route lang="yaml">
name: Demo
layout: default
style:
  navigationBarTitleText: Demo
tabBar:
  iconPath: static/images/tabBar/demo.png
  selectedIconPath: static/images/tabBar/selectedDemo.png
</route> 
```

### 推荐的解决方案

none

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。
